# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6af204d1ed80422da57289100c387a83a6cf4b61aa188c0b0a944059564f0572febc37b627c6a8bddc8138abb448c0c5aba5747c15fe41241db36eb225995dce
  superadmin_name: Super Admin
  superadmin_email: superadmin@admin.com
  superadmin_password: S1U2P3E4R5U6S7E8R

test:
  secret_key_base: 55464f16a7764870aa679df11dad77a223ab7a0b7b7e69e28ae4df52ca6a57098173c2b3b1266fe6d82bf6cb59cacd5c71fd35f0f232f0902ce2900c5d39c12c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  superadmin_name: <%= ENV["SUPERADMIN_NAME"] %>
  superadmin_email: <%= ENV["SUPERADMIN_EMAIL"] %>
  superadmin_password: <%= ENV["SUPERADMIN_PASSWORD"] %>
